"""removed author field(relationship) from book

Revision ID: 3df8a3a30499
Revises: 9241c6ad8e0a
Create Date: 2025-06-17 19:33:27.477893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df8a3a30499'
down_revision: Union[str, Sequence[str], None] = '9241c6ad8e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
